<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0;netstandard2.0</TargetFrameworks>
        <LangVersion>12</LangVersion>
        <Nullable>enable</Nullable>
        <Description>A plugin for ChibiRuby that enables conversion between C# and mruby objects.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ChibiRuby.Serializer.Tests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChibiRuby\ChibiRuby.csproj" />
      <ProjectReference Include="..\ChibiRuby.Serializer.SourceGenerator\ChibiRuby.Serializer.SourceGenerator.csproj">
          <OutputItemType>Analyzer</OutputItemType>
          <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      </ProjectReference>
    </ItemGroup>

    <!-- Bundle SourceGenerator -->
    <ItemGroup>
        <None Include="..\ChibiRuby.Serializer.SourceGenerator\bin\$(Configuration)\netstandard2.0\ChibiRuby.Serializer.SourceGenerator.dll"
              PackagePath="analyzers\dotnet\roslyn4.1\cs"
              Pack="true"
              Visible="false" />
    </ItemGroup>

    <Import Project="..\Polyfills.props" />
    <ItemGroup>
        <ProjectReference Include="..\ChibiRuby.Polyfills\ChibiRuby.Polyfills.csproj" />
    </ItemGroup>
</Project>
