<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0;netstandard2.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RuntimeIdentifiers>osx-arm64;osx-x64;linux-x64;linux-arm64;win-x64;android-arm64;android-x64;ios-arm64;iossimulator-arm64;browser-wasm</RuntimeIdentifiers>
        <LangVersion>13</LangVersion>
        <Description>Native binding for the mruby compiler for use from C# and ChibiRuby</Description>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ChibiRuby.Tests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChibiRuby\ChibiRuby.csproj" />
    </ItemGroup>


    <ItemGroup>
      <None Include="runtimes\**\*.dll;runtimes\**\*.so;runtimes\**\*.dylib;runtimes\**\*.a">
        <Pack>true</Pack>
        <PackagePath>%(Identity)</PackagePath>
      </None>
    </ItemGroup>

    <PropertyGroup>
        <_MRubyCompilerHostRid Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</_MRubyCompilerHostRid>
        <_MRubyCompilerHostRid Condition="'$(_MRubyCompilerHostRid)' == ''">$(NETCoreSdkRuntimeIdentifier)</_MRubyCompilerHostRid>
    </PropertyGroup>
    <ItemGroup Condition="'$(_MRubyCompilerHostRid)' != '' And Exists('runtimes\$(_MRubyCompilerHostRid)\native')">
        <None Update="runtimes\$(_MRubyCompilerHostRid)\native\libmruby.*">
            <Link>%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Visible>false</Visible>
        </None>
    </ItemGroup>


    <Import Project="..\Polyfills.props" />
    <ItemGroup>
        <ProjectReference Include="..\ChibiRuby.Polyfills\ChibiRuby.Polyfills.csproj" />
    </ItemGroup>
</Project>
