// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace ChibiRuby.Debugger.Dap.Protocol;

public sealed class NoJsonSerializerOptions
{
    public static NoJsonSerializerOptions Default { get; } = new();

    public bool StrictExtraProperties { get; init; }
    public bool WriteIndented { get; init; }
    public bool SkipNullProperties { get; init; } = true;
}

public sealed class NoJsonFormatException : global::System.Exception
{
    public NoJsonFormatException(string message, int position, int line = 0, int column = 0)
        : base(FormatMessage(message, position, line, column))
    {
        Position = position;
        Line = line;
        Column = column;
    }

    /// <summary>Byte offset within the input where the failure was detected.</summary>
    public int Position { get; }

    /// <summary>1-based line number; 0 when not computed (e.g. constructed directly without source span).</summary>
    public int Line { get; }

    /// <summary>1-based column number on <see cref="Line"/>; 0 when not computed.</summary>
    public int Column { get; }

    static string FormatMessage(string message, int position, int line, int column) =>
        line > 0
            ? message + " (line " + line + ", column " + column + ", pos " + position + ")"
            : message + " (pos " + position + ")";
}

/// <summary>
/// Pull-style UTF-8 JSON tokenizer with a Read*/TryRead* only API surface:
/// the caller (generated formatters) always knows the expected next token from the schema.
/// </summary>
ref struct Utf8JsonTokenizer
{
#if NET7_0_OR_GREATER
    // C# 11 ref-byte field: zero indirection on hot reads.
    readonly ref byte head;
#else
    // Pre-net7 targets (netstandard 2.1) don't allow ref fields. Hold the span and recover the
    // ref on-demand via MemoryMarshal.GetReference — JIT inlines `HeadRef()` to the same code.
    readonly global::System.ReadOnlySpan<byte> input;
#endif
    readonly int length;
    int pos;
    int valueStart;
    int valueEnd;
    bool valueHasEscape;

    public Utf8JsonTokenizer(global::System.ReadOnlySpan<byte> input)
    {
#if NET7_0_OR_GREATER
        head = ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(input);
#else
        this.input = input;
#endif
        length = input.Length;
        pos = 0;
        valueStart = 0;
        valueEnd = 0;
        valueHasEscape = false;
    }

    /// <summary>Recover a writable <c>ref byte</c> at index 0 of the input span.</summary>
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    ref byte HeadRef() =>
#if NET7_0_OR_GREATER
        ref head;
#else
        ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(input);
#endif

    public int Position
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => pos;
    }

    // ----- Structural -----------------------------------------------------------------------

    public void ReadStartObject()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'{')
            ThrowFormatException("Expected '{'");
        pos++;
    }

    public void ReadStartArray()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'[')
            ThrowFormatException("Expected '['");
        pos++;
    }

    /// <summary>
    /// Inside an object: read the next property name into <paramref name="nameUtf8"/> and the
    /// trailing colon, or return false (and consume the closing '}') when the object ends.
    /// </summary>
    public bool TryReadPropertyName(out global::System.ReadOnlySpan<byte> nameUtf8)
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end inside object");

        byte b = ByteAt(pos);
        if (b == (byte)',')
        {
            pos++;
            SkipWhitespace();
            if (pos >= length) ThrowFormatException("Unexpected end after ','");
            b = ByteAt(pos);
        }

        if (b == (byte)'}')
        {
            pos++;
            nameUtf8 = default;
            return false;
        }

        if (b != (byte)'"')
            ThrowFormatException("Expected '\"' for property name, got 0x" + b.ToString("X2"));

        ReadStringValue();
        nameUtf8 = SliceFrom(valueStart, valueEnd - valueStart);

        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)':')
            ThrowFormatException("Expected ':' after property name");
        pos++;
        return true;
    }

    /// <summary>
    /// Inside an array: consume the optional ',' separator. Returns true and consumes the
    /// closing ']' if the array ended; false when another element follows.
    /// </summary>
    public bool TryReadEndArray()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end inside array");

        byte b = ByteAt(pos);
        if (b == (byte)',')
        {
            pos++;
            SkipWhitespace();
            if (pos >= length) ThrowFormatException("Unexpected end after ','");
            b = ByteAt(pos);
        }

        if (b == (byte)']') { pos++; return true; }
        return false;
    }

    // ----- Optional/null --------------------------------------------------------------------

    /// <summary>If the next token is JSON <c>null</c>, advance past it and return true.</summary>
    public bool TryReadNull()
    {
        SkipWhitespace();
        if (pos + 4 <= length && ByteAt(pos) == (byte)'n'
            && SliceFrom(pos, 4).SequenceEqual("null"u8))
        {
            pos += 4;
            return true;
        }
        return false;
    }

    // ----- Value readers --------------------------------------------------------------------

    public string ReadString()
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'"')
            ThrowFormatException("Expected string");
        ReadStringValue();
        var span = SliceFrom(valueStart, valueEnd - valueStart);
        return valueHasEscape ? DecodeString(span) : global::System.Text.Encoding.UTF8.GetString(span);
    }

    /// <summary>
    /// Read a JSON string and return its raw UTF-8 byte slice without allocating a <c>string</c>.
    /// Returns false if the string contains backslash escapes — callers should then fall back to <see cref="ReadString"/>.
    /// </summary>
    public bool TryReadStringRaw(out global::System.ReadOnlySpan<byte> rawBytes)
    {
        SkipWhitespace();
        if (pos >= length || ByteAt(pos) != (byte)'"')
            ThrowFormatException("Expected string");
        ReadStringValue();
        if (valueHasEscape) { rawBytes = default; return false; }
        rawBytes = SliceFrom(valueStart, valueEnd - valueStart);
        return true;
    }

    public bool ReadBoolean()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Expected boolean");
        byte b = ByteAt(pos);
        if (b == (byte)'t')
        {
            if (pos + 4 > length || !SliceFrom(pos, 4).SequenceEqual("true"u8))
                ThrowFormatException("Expected 'true'");
            pos += 4;
            return true;
        }
        if (b == (byte)'f')
        {
            if (pos + 5 > length || !SliceFrom(pos, 5).SequenceEqual("false"u8))
                ThrowFormatException("Expected 'false'");
            pos += 5;
            return false;
        }
        ThrowFormatException("Expected boolean, got 0x" + b.ToString("X2"));
        return false; // unreachable — the C# flow analyser doesn't honour [DoesNotReturn] for CS0161.
    }

    public sbyte ReadSByte()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out sbyte v, out _))
            ThrowFormatException("Invalid int8");
        return v;
    }

    public byte ReadByte()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out byte v, out _))
            ThrowFormatException("Invalid uint8");
        return v;
    }

    public short ReadInt16()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out short v, out _))
            ThrowFormatException("Invalid int16");
        return v;
    }

    public ushort ReadUInt16()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out ushort v, out _))
            ThrowFormatException("Invalid uint16");
        return v;
    }

    public int ReadInt32()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out int v, out _))
            ThrowFormatException("Invalid int32");
        return v;
    }

    public uint ReadUInt32()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out uint v, out _))
            ThrowFormatException("Invalid uint32");
        return v;
    }

    public long ReadInt64()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out long v, out _))
            ThrowFormatException("Invalid int64");
        return v;
    }

    public ulong ReadUInt64()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out ulong v, out _))
            ThrowFormatException("Invalid uint64");
        return v;
    }

    public float ReadSingle()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out float v, out _))
            ThrowFormatException("Invalid float");
        return v;
    }

    public double ReadDouble()
    {
        ReadNumberValue();
        if (!global::System.Buffers.Text.Utf8Parser.TryParse(
                SliceFrom(valueStart, valueEnd - valueStart), out double v, out _))
            ThrowFormatException("Invalid double");
        return v;
    }

    public global::System.DateTimeOffset ReadDateTimeOffset()
    {
        var s = ReadString();
        if (!global::System.DateTimeOffset.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.RoundtripKind, out var v))
            ThrowFormatException("Invalid date-time '" + s + "'");
        return v;
    }

    public global::System.Guid ReadGuid()
    {
        var s = ReadString();
        if (!global::System.Guid.TryParse(s, out var v))
            ThrowFormatException("Invalid uuid '" + s + "'");
        return v;
    }

#if NET6_0_OR_GREATER
    public global::System.DateOnly ReadDateOnly()
    {
        var s = ReadString();
        if (!global::System.DateOnly.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.None, out var v))
            ThrowFormatException("Invalid date '" + s + "'");
        return v;
    }

    public global::System.TimeOnly ReadTimeOnly()
    {
        var s = ReadString();
        if (!global::System.TimeOnly.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, global::System.Globalization.DateTimeStyles.None, out var v))
            ThrowFormatException("Invalid time '" + s + "'");
        return v;
    }
#endif

    public global::System.TimeSpan ReadTimeSpan()
    {
        var s = ReadString();
        // ISO 8601 duration ("PT1H30M") via XmlConvert — JSON Schema's `format: duration` mandates ISO 8601.
        try { return global::System.Xml.XmlConvert.ToTimeSpan(s); }
        catch (global::System.FormatException) { ThrowFormatException("Invalid duration '" + s + "'"); return default; }
    }

    public global::System.Uri ReadUri()
    {
        var s = ReadString();
        if (!global::System.Uri.TryCreate(s, global::System.UriKind.RelativeOrAbsolute, out var v))
            ThrowFormatException("Invalid uri '" + s + "'");
        return v;
    }

    public byte[] ReadByteArray()
    {
        var s = ReadString();
        try { return global::System.Convert.FromBase64String(s); }
        catch (global::System.FormatException) { ThrowFormatException("Invalid base64"); return []; }
    }

    // ----- Discriminator peek (polymorphic dispatch) ---------------------------------------

    /// <summary>
    /// Scan forward (without advancing the tokenizer state) for a top-level property named
    /// <paramref name="discriminatorName"/> on the current object, and return its raw UTF-8 string
    /// value via <paramref name="rawValue"/>. The caller must still be positioned just after the
    /// <c>{</c> of the object (i.e. inside it). The scan does not validate the rest of the object;
    /// it just hunts the discriminator so a polymorphic parser can dispatch to the right subtype.
    /// </summary>
    public bool TryPeekDiscriminator(
        global::System.ReadOnlySpan<byte> discriminatorName,
        out global::System.ReadOnlySpan<byte> rawValue)
    {
        rawValue = default;
        var savedPos = pos;
        var savedValueStart = valueStart;
        var savedValueEnd = valueEnd;
        var savedValueHasEscape = valueHasEscape;
        try
        {
            int depth = 0;
            while (pos < length)
            {
                SkipWhitespace();
                if (pos >= length) return false;
                byte b = ByteAt(pos);

                if (b == (byte)'{') { depth++; pos++; continue; }
                if (b == (byte)'}')
                {
                    if (depth == 0) return false; // current object ended
                    depth--; pos++; continue;
                }
                if (b == (byte)'[') { SkipObjectOrArray((byte)'[', (byte)']'); continue; }
                if (b == (byte)',' || b == (byte)':') { pos++; continue; }

                if (b != (byte)'"')
                {
                    // Skip scalar values quickly until we land on a property name or container.
                    while (pos < length)
                    {
                        var bb = ByteAt(pos);
                        if (bb == (byte)',' || bb == (byte)'}' || bb == (byte)']' || bb == (byte)' '
                            || bb == (byte)'\n' || bb == (byte)'\t' || bb == (byte)'\r') break;
                        pos++;
                    }
                    continue;
                }

                // We're on a string. Inside the *current* object (depth == 0) it's a property name;
                // anywhere deeper it's a string value to skip past.
                ReadStringValue();
                if (depth != 0) continue;

                var nameSpan = SliceFrom(valueStart, valueEnd - valueStart);

                // After the name, expect ':'.
                SkipWhitespace();
                if (pos >= length || ByteAt(pos) != (byte)':') return false;
                pos++;

                if (nameSpan.SequenceEqual(discriminatorName) && !valueHasEscape)
                {
                    SkipWhitespace();
                    if (pos >= length || ByteAt(pos) != (byte)'"') return false;
                    ReadStringValue();
                    if (valueHasEscape) return false; // peek does not unescape
                    rawValue = SliceFrom(valueStart, valueEnd - valueStart);
                    return true;
                }

                // Not the discriminator — skip the value and continue scanning.
                SkipWhitespace();
                if (pos >= length) return false;
                byte valStart = ByteAt(pos);
                if (valStart == (byte)'{') SkipObjectOrArray((byte)'{', (byte)'}');
                else if (valStart == (byte)'[') SkipObjectOrArray((byte)'[', (byte)']');
                else if (valStart == (byte)'"') ReadStringValue();
                else
                {
                    while (pos < length)
                    {
                        var bb = ByteAt(pos);
                        if (bb == (byte)',' || bb == (byte)'}' || bb == (byte)' '
                            || bb == (byte)'\n' || bb == (byte)'\t' || bb == (byte)'\r') break;
                        pos++;
                    }
                }
            }
            return false;
        }
        finally
        {
            pos = savedPos;
            valueStart = savedValueStart;
            valueEnd = savedValueEnd;
            valueHasEscape = savedValueHasEscape;
        }
    }

    // ----- Skip an unknown value -----------------------------------------------------------

    public void SkipValue()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Unexpected end of input");
        byte b = ByteAt(pos);
        switch (b)
        {
            case (byte)'"': ReadStringValue(); return;
            case (byte)'{': SkipObjectOrArray((byte)'{', (byte)'}'); return;
            case (byte)'[': SkipObjectOrArray((byte)'[', (byte)']'); return;
            case (byte)'t': ConsumeKeyword("true"u8); return;
            case (byte)'f': ConsumeKeyword("false"u8); return;
            case (byte)'n': ConsumeKeyword("null"u8); return;
            default:
                if (b == (byte)'-' || (b >= (byte)'0' && b <= (byte)'9')) { ReadNumberValue(); return; }
                ThrowFormatException("Unexpected byte 0x" + b.ToString("X2"));
                return; // unreachable
        }
    }

    // ----- Internal helpers ----------------------------------------------------------------

    /// <summary>
    /// Throw a <see cref="NoJsonFormatException"/> annotated with the current position plus the
    /// 1-based line / column computed from the input span. Kept as a NoInlining void helper so the
    /// callers stay JIT-inlineable — `throw new ...` expressions inline far worse than a single
    /// method-call to a cold throw routine.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    public void ThrowFormatException(string message)
    {
        var (line, column) = ComputeLineColumn(pos);
        throw new NoJsonFormatException(message, pos, line, column);
    }

    (int Line, int Column) ComputeLineColumn(int position)
    {
        int line = 1, col = 1;
        var max = position < length ? position : length;
        for (int i = 0; i < max; i++)
        {
            if (ByteAt(i) == (byte)'\n') { line++; col = 1; }
            else col++;
        }
        return (line, col);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    byte ByteAt(int offset) => global::System.Runtime.CompilerServices.Unsafe.Add(ref HeadRef(), offset);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    global::System.ReadOnlySpan<byte> SliceFrom(int offset, int len) =>
#if NET7_0_OR_GREATER
        global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(
            ref global::System.Runtime.CompilerServices.Unsafe.Add(ref HeadRef(), offset),
            len);
#else
        global::ChibiRuby.Polyfills.MemoryMarshalEx.CreateReadOnlySpan(
            ref global::System.Runtime.CompilerServices.Unsafe.Add(ref HeadRef(), offset),
            len);
#endif

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void SkipWhitespace()
    {
        while (pos < length)
        {
            byte b = ByteAt(pos);
            if (b == (byte)' ' || b == (byte)'\t' || b == (byte)'\n' || b == (byte)'\r') pos++;
            else break;
        }
    }

    /// <summary>Consume <c>"..."</c> at <c>pos</c> (opening quote required), recording valueStart/valueEnd.</summary>
    void ReadStringValue()
    {
        pos++; // skip opening quote
        valueStart = pos;
        valueHasEscape = false;
        while (pos < length)
        {
            byte b = ByteAt(pos);
            if (b == (byte)'"')
            {
                valueEnd = pos;
                pos++;
                return;
            }
            if (b == (byte)'\\')
            {
                valueHasEscape = true;
                if (pos + 1 >= length) ThrowFormatException("Truncated escape");
                byte next = ByteAt(pos + 1);
                pos += (next == (byte)'u') ? 6 : 2;
                continue;
            }
            pos++;
        }
        ThrowFormatException("Unterminated string");
    }

    void ReadNumberValue()
    {
        SkipWhitespace();
        if (pos >= length) ThrowFormatException("Expected number");
        byte first = ByteAt(pos);
        if (first != (byte)'-' && !(first >= (byte)'0' && first <= (byte)'9'))
            ThrowFormatException("Expected number, got 0x" + first.ToString("X2"));

        valueStart = pos;
        if (first == (byte)'-') pos++;
        while (pos < length && IsNumberByte(ByteAt(pos))) pos++;
        valueEnd = pos;
    }

    void ConsumeKeyword(global::System.ReadOnlySpan<byte> keyword)
    {
        if (pos + keyword.Length > length || !SliceFrom(pos, keyword.Length).SequenceEqual(keyword))
            ThrowFormatException("Expected '" + global::System.Text.Encoding.ASCII.GetString(keyword) + "'");
        pos += keyword.Length;
    }

    void SkipObjectOrArray(byte open, byte close)
    {
        int depth = 1;
        pos++; // consume the opening byte
        while (pos < length && depth > 0)
        {
            byte b = ByteAt(pos);
            if (b == (byte)'"') { ReadStringValue(); continue; }
            if (b == open) { depth++; pos++; continue; }
            if (b == close) { depth--; pos++; continue; }
            pos++;
        }
        if (depth != 0) ThrowFormatException("Unterminated container");
    }

    static bool IsNumberByte(byte b) =>
        (b >= (byte)'0' && b <= (byte)'9') || b == (byte)'.' || b == (byte)'-' || b == (byte)'+' || b == (byte)'e' || b == (byte)'E';

    static string DecodeString(global::System.ReadOnlySpan<byte> bytes)
    {
        var sb = new global::System.Text.StringBuilder(bytes.Length);
        int i = 0;
        while (i < bytes.Length)
        {
            byte b = bytes[i];
            if (b != (byte)'\\') { sb.Append((char)b); i++; continue; }

            if (i + 1 >= bytes.Length) throw new NoJsonFormatException("Truncated escape", i);
            byte e = bytes[i + 1];
            switch (e)
            {
                case (byte)'"':  sb.Append('"');  i += 2; break;
                case (byte)'\\': sb.Append('\\'); i += 2; break;
                case (byte)'/':  sb.Append('/');  i += 2; break;
                case (byte)'b':  sb.Append('\b'); i += 2; break;
                case (byte)'f':  sb.Append('\f'); i += 2; break;
                case (byte)'n':  sb.Append('\n'); i += 2; break;
                case (byte)'r':  sb.Append('\r'); i += 2; break;
                case (byte)'t':  sb.Append('\t'); i += 2; break;
                case (byte)'u':
                {
                    if (i + 6 > bytes.Length) throw new NoJsonFormatException("Truncated \\u escape", i);
                    int cp = HexNibble(bytes[i + 2]) << 12
                           | HexNibble(bytes[i + 3]) << 8
                           | HexNibble(bytes[i + 4]) << 4
                           | HexNibble(bytes[i + 5]);
                    sb.Append((char)cp);
                    i += 6;
                    break;
                }
                default: throw new NoJsonFormatException("Unknown escape", i);
            }
        }
        return sb.ToString();
    }

    static int HexNibble(byte b)
    {
        if (b >= (byte)'0' && b <= (byte)'9') return b - (byte)'0';
        if (b >= (byte)'a' && b <= (byte)'f') return 10 + (b - (byte)'a');
        if (b >= (byte)'A' && b <= (byte)'F') return 10 + (b - (byte)'A');
        throw new NoJsonFormatException("Bad hex digit", 0);
    }
}

ref struct Utf8JsonBufferWriter
{
    readonly global::System.Buffers.IBufferWriter<byte> writer;
#if NET7_0_OR_GREATER
    // C# 11 ref-byte field — moves forward via `Unsafe.Add` on every Advance.
    ref byte bufferReference;
#else
    // Pre-net7: hold the rented span (no separate offset — slicing advances the view).
    global::System.Span<byte> bufferReference;
#endif
    int spanRemaining;
    int pending;
    bool needsSeparator;

    public Utf8JsonBufferWriter(global::System.Buffers.IBufferWriter<byte> writer)
    {
        this.writer = writer;
#if NET7_0_OR_GREATER
        bufferReference = ref global::System.Runtime.CompilerServices.Unsafe.NullRef<byte>();
#else
        bufferReference = default;
#endif
        spanRemaining = 0;
        pending = 0;
        needsSeparator = false;
    }

    public void Flush()
    {
        if (pending > 0)
        {
            writer.Advance(pending);
#if NET7_0_OR_GREATER
            bufferReference = ref global::System.Runtime.CompilerServices.Unsafe.NullRef<byte>();
#else
            bufferReference = default;
#endif
            spanRemaining = 0;
            pending = 0;
        }
    }

    /// <summary>Writable <c>ref byte</c> at <paramref name="offset"/> past the current write head.
    /// JIT-inlines to a single ADD on net7+, and to <c>MemoryMarshal.GetReference + offset</c> on
    /// netstandard. Callers use it as the LHS of an assignment (e.g. <c>GetByte(3) = b;</c>).</summary>
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    ref byte GetByte(int offset) =>
#if NET7_0_OR_GREATER
        ref global::System.Runtime.CompilerServices.Unsafe.Add(ref bufferReference, offset);
#else
        ref global::System.Runtime.CompilerServices.Unsafe.Add(
            ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(bufferReference),
            offset);
#endif

    public void WriteStartObject() { MaybeSeparator(); AppendByte((byte)'{'); needsSeparator = false; }
    public void WriteEndObject()   { needsSeparator = false; AppendByte((byte)'}'); needsSeparator = true; }
    public void WriteStartArray()  { MaybeSeparator(); AppendByte((byte)'['); needsSeparator = false; }
    public void WriteEndArray()    { needsSeparator = false; AppendByte((byte)']'); needsSeparator = true; }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public void WritePropertyNameRaw(global::System.ReadOnlySpan<byte> nameWithQuotesAndColon)
    {
        MaybeSeparator();
        Append(nameWithQuotesAndColon);
        needsSeparator = false;
    }

    /// <summary>
    /// Writes <paramref name="contentInsideQuotes"/> as a JSON string value. The bytes must be valid UTF-8
    /// and contain no characters that would require escaping (used for enum members and other fixed literals).
    /// </summary>
    public void WriteRawStringValue(scoped global::System.ReadOnlySpan<byte> contentInsideQuotes)
    {
        MaybeSeparator();
        AppendByte((byte)'"');
        Append(contentInsideQuotes);
        AppendByte((byte)'"');
        needsSeparator = true;
    }

    public void WriteNull()  { MaybeSeparator(); Append("null"u8);  needsSeparator = true; }
    public void WriteTrue()  { MaybeSeparator(); Append("true"u8);  needsSeparator = true; }
    public void WriteFalse() { MaybeSeparator(); Append("false"u8); needsSeparator = true; }
    public void WriteBoolean(bool v) { if (v) WriteTrue(); else WriteFalse(); }

    public void WriteDateTimeOffset(global::System.DateTimeOffset v)
    {
        WriteString(v.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteGuid(global::System.Guid v)
    {
        WriteString(v.ToString("D", global::System.Globalization.CultureInfo.InvariantCulture));
    }

#if NET6_0_OR_GREATER
    public void WriteDateOnly(global::System.DateOnly v)
    {
        WriteString(v.ToString("yyyy-MM-dd", global::System.Globalization.CultureInfo.InvariantCulture));
    }

    public void WriteTimeOnly(global::System.TimeOnly v)
    {
        WriteString(v.ToString("O", global::System.Globalization.CultureInfo.InvariantCulture));
    }
#endif

    public void WriteTimeSpan(global::System.TimeSpan v)
    {
        // Emit ISO 8601 duration (`P…T…`) so it round-trips through `format: duration` consumers.
        WriteString(global::System.Xml.XmlConvert.ToString(v));
    }

    public void WriteUri(global::System.Uri v)
    {
        WriteString(v.ToString());
    }

    public void WriteByteArray(byte[] v)
    {
        WriteString(global::System.Convert.ToBase64String(v));
    }

    public void WriteSByte(sbyte v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("sbyte format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteByte(byte v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("byte format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt16(short v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("short format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt16(ushort v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[8];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("ushort format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt32(int v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[16];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("int format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt32(uint v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[16];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("uint format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteInt64(long v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[24];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("long format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteUInt64(ulong v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[24];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("ulong format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteSingle(float v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[32];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("single format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteDouble(double v)
    {
        MaybeSeparator();
        global::System.Span<byte> tmp = stackalloc byte[32];
        if (!global::System.Buffers.Text.Utf8Formatter.TryFormat(v, tmp, out int written))
            throw new global::System.InvalidOperationException("double format");
        Append(tmp.Slice(0, written));
        needsSeparator = true;
    }

    public void WriteString(string value)
    {
        MaybeSeparator();
        AppendByte((byte)'"');

        var chars = value.AsSpan();
        int safeStart = 0;
        for (int i = 0; i < chars.Length; i++)
        {
            char c = chars[i];
            if (c >= 0x20 && c < 0x80 && c != '"' && c != '\\') continue;

            if (i > safeStart) AppendAsciiRange(chars.Slice(safeStart, i - safeStart));

            switch (c)
            {
                case '"':  Append2((byte)'\\', (byte)'"');  break;
                case '\\': Append2((byte)'\\', (byte)'\\'); break;
                case '\b': Append2((byte)'\\', (byte)'b');  break;
                case '\f': Append2((byte)'\\', (byte)'f');  break;
                case '\n': Append2((byte)'\\', (byte)'n');  break;
                case '\r': Append2((byte)'\\', (byte)'r');  break;
                case '\t': Append2((byte)'\\', (byte)'t');  break;
                default:
                    if (c < 0x20)
                    {
                        Ensure(6);
                        GetByte(0) = (byte)'\\';
                        GetByte(1) = (byte)'u';
                        GetByte(2) = (byte)'0';
                        GetByte(3) = (byte)'0';
                        GetByte(4) = HexByte((c >> 4) & 0xF);
                        GetByte(5) = HexByte(c & 0xF);
                        Advance(6);
                    }
                    else
                    {
                        int cp;
                        if (char.IsHighSurrogate(c) && i + 1 < chars.Length && char.IsLowSurrogate(chars[i + 1]))
                        {
                            cp = char.ConvertToUtf32(c, chars[i + 1]);
                            i++;
                        }
                        else cp = c;
                        WriteCodePointUtf8(cp);
                    }
                    break;
            }
            safeStart = i + 1;
        }

        if (chars.Length > safeStart) AppendAsciiRange(chars.Slice(safeStart));

        AppendByte((byte)'"');
        needsSeparator = true;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    static byte HexByte(int nibble) => nibble < 10 ? (byte)('0' + nibble) : (byte)('a' + nibble - 10);

    void AppendAsciiRange(scoped global::System.ReadOnlySpan<char> chars)
    {
        Ensure(chars.Length);
#if NET7_0_OR_GREATER
        var destSpan = global::System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref bufferReference, chars.Length);
#else
        // Slice already-pinned span — bufferReference's start is already the write head.
        var destSpan = bufferReference.Slice(0, chars.Length);
#endif
        int written = global::System.Text.Encoding.UTF8.GetBytes(chars, destSpan);
        Advance(written);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Append2(byte b0, byte b1)
    {
        Ensure(2);
        GetByte(0) = b0;
        GetByte(1) = b1;
        Advance(2);
    }

    void WriteCodePointUtf8(int cp)
    {
        if (cp < 0x800)
        {
            Ensure(2);
            GetByte(0) = (byte)(0xC0 | (cp >> 6));
            GetByte(1) = (byte)(0x80 | (cp & 0x3F));
            Advance(2);
        }
        else if (cp < 0x10000)
        {
            Ensure(3);
            GetByte(0) = (byte)(0xE0 | (cp >> 12));
            GetByte(1) = (byte)(0x80 | ((cp >> 6) & 0x3F));
            GetByte(2) = (byte)(0x80 | (cp & 0x3F));
            Advance(3);
        }
        else
        {
            Ensure(4);
            GetByte(0) = (byte)(0xF0 | (cp >> 18));
            GetByte(1) = (byte)(0x80 | ((cp >> 12) & 0x3F));
            GetByte(2) = (byte)(0x80 | ((cp >> 6) & 0x3F));
            GetByte(3) = (byte)(0x80 | (cp & 0x3F));
            Advance(4);
        }
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void MaybeSeparator()
    {
        if (needsSeparator) AppendByte((byte)',');
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Append(scoped global::System.ReadOnlySpan<byte> data)
    {
        Ensure(data.Length);
        global::System.Runtime.CompilerServices.Unsafe.CopyBlockUnaligned(
            ref GetByte(0),
            ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(data),
            (uint)data.Length);
        Advance(data.Length);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void AppendByte(byte b)
    {
        Ensure(1);
        GetByte(0) = b;
        Advance(1);
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    void Advance(int n)
    {
#if NET7_0_OR_GREATER
        bufferReference = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref bufferReference, n);
#else
        // Span tracks the head itself via slicing — no separate offset to bump.
        bufferReference = bufferReference.Slice(n);
#endif
        spanRemaining -= n;
        pending += n;
    }

    void Ensure(int needed)
    {
        if (spanRemaining >= needed) return;
        Flush();
        var newSpan = writer.GetSpan(needed > 256 ? needed : 256);
#if NET7_0_OR_GREATER
        bufferReference = ref global::System.Runtime.InteropServices.MemoryMarshal.GetReference(newSpan);
#else
        bufferReference = newSpan;
#endif
        spanRemaining = newSpan.Length;
    }
}

public static class ProtocolSerializer
{
    delegate T DeserializeDelegate<T>(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options);
    delegate void SerializeDelegate<T>(global::System.Buffers.IBufferWriter<byte> writer, in T value, NoJsonSerializerOptions options);
    
    static readonly global::System.Collections.Generic.Dictionary<global::System.Type, (object Deserialize, object Serialize)> Formatters = new(96)
    {
        [typeof(ProtocolMessage)] = ((DeserializeDelegate<ProtocolMessage>)ProtocolMessageFormatter.Deserialize, (SerializeDelegate<ProtocolMessage>)ProtocolMessageFormatter.Serialize),
        [typeof(Request)] = ((DeserializeDelegate<Request>)RequestFormatter.Deserialize, (SerializeDelegate<Request>)RequestFormatter.Serialize),
        [typeof(Event)] = ((DeserializeDelegate<Event>)EventFormatter.Deserialize, (SerializeDelegate<Event>)EventFormatter.Serialize),
        [typeof(Response)] = ((DeserializeDelegate<Response>)ResponseFormatter.Deserialize, (SerializeDelegate<Response>)ResponseFormatter.Serialize),
        [typeof(ErrorResponseBody)] = ((DeserializeDelegate<ErrorResponseBody>)ErrorResponseBodyFormatter.Deserialize, (SerializeDelegate<ErrorResponseBody>)ErrorResponseBodyFormatter.Serialize),
        [typeof(ErrorResponse)] = ((DeserializeDelegate<ErrorResponse>)ErrorResponseFormatter.Deserialize, (SerializeDelegate<ErrorResponse>)ErrorResponseFormatter.Serialize),
        [typeof(InitializedEvent)] = ((DeserializeDelegate<InitializedEvent>)InitializedEventFormatter.Deserialize, (SerializeDelegate<InitializedEvent>)InitializedEventFormatter.Serialize),
        [typeof(StoppedEventBody)] = ((DeserializeDelegate<StoppedEventBody>)StoppedEventBodyFormatter.Deserialize, (SerializeDelegate<StoppedEventBody>)StoppedEventBodyFormatter.Serialize),
        [typeof(StoppedEvent)] = ((DeserializeDelegate<StoppedEvent>)StoppedEventFormatter.Deserialize, (SerializeDelegate<StoppedEvent>)StoppedEventFormatter.Serialize),
        [typeof(ContinuedEventBody)] = ((DeserializeDelegate<ContinuedEventBody>)ContinuedEventBodyFormatter.Deserialize, (SerializeDelegate<ContinuedEventBody>)ContinuedEventBodyFormatter.Serialize),
        [typeof(ContinuedEvent)] = ((DeserializeDelegate<ContinuedEvent>)ContinuedEventFormatter.Deserialize, (SerializeDelegate<ContinuedEvent>)ContinuedEventFormatter.Serialize),
        [typeof(TerminatedEventBody)] = ((DeserializeDelegate<TerminatedEventBody>)TerminatedEventBodyFormatter.Deserialize, (SerializeDelegate<TerminatedEventBody>)TerminatedEventBodyFormatter.Serialize),
        [typeof(TerminatedEvent)] = ((DeserializeDelegate<TerminatedEvent>)TerminatedEventFormatter.Deserialize, (SerializeDelegate<TerminatedEvent>)TerminatedEventFormatter.Serialize),
        [typeof(OutputEventBody)] = ((DeserializeDelegate<OutputEventBody>)OutputEventBodyFormatter.Deserialize, (SerializeDelegate<OutputEventBody>)OutputEventBodyFormatter.Serialize),
        [typeof(OutputEventBodyGroup)] = ((DeserializeDelegate<OutputEventBodyGroup>)OutputEventBodyGroupFormatter.Deserialize, (SerializeDelegate<OutputEventBodyGroup>)OutputEventBodyGroupFormatter.Serialize),
        [typeof(OutputEvent)] = ((DeserializeDelegate<OutputEvent>)OutputEventFormatter.Deserialize, (SerializeDelegate<OutputEvent>)OutputEventFormatter.Serialize),
        [typeof(InitializeRequest)] = ((DeserializeDelegate<InitializeRequest>)InitializeRequestFormatter.Deserialize, (SerializeDelegate<InitializeRequest>)InitializeRequestFormatter.Serialize),
        [typeof(InitializeRequestArguments)] = ((DeserializeDelegate<InitializeRequestArguments>)InitializeRequestArgumentsFormatter.Deserialize, (SerializeDelegate<InitializeRequestArguments>)InitializeRequestArgumentsFormatter.Serialize),
        [typeof(InitializeResponse)] = ((DeserializeDelegate<InitializeResponse>)InitializeResponseFormatter.Deserialize, (SerializeDelegate<InitializeResponse>)InitializeResponseFormatter.Serialize),
        [typeof(ConfigurationDoneRequest)] = ((DeserializeDelegate<ConfigurationDoneRequest>)ConfigurationDoneRequestFormatter.Deserialize, (SerializeDelegate<ConfigurationDoneRequest>)ConfigurationDoneRequestFormatter.Serialize),
        [typeof(ConfigurationDoneArguments)] = ((DeserializeDelegate<ConfigurationDoneArguments>)ConfigurationDoneArgumentsFormatter.Deserialize, (SerializeDelegate<ConfigurationDoneArguments>)ConfigurationDoneArgumentsFormatter.Serialize),
        [typeof(ConfigurationDoneResponse)] = ((DeserializeDelegate<ConfigurationDoneResponse>)ConfigurationDoneResponseFormatter.Deserialize, (SerializeDelegate<ConfigurationDoneResponse>)ConfigurationDoneResponseFormatter.Serialize),
        [typeof(LaunchRequest)] = ((DeserializeDelegate<LaunchRequest>)LaunchRequestFormatter.Deserialize, (SerializeDelegate<LaunchRequest>)LaunchRequestFormatter.Serialize),
        [typeof(LaunchRequestArguments)] = ((DeserializeDelegate<LaunchRequestArguments>)LaunchRequestArgumentsFormatter.Deserialize, (SerializeDelegate<LaunchRequestArguments>)LaunchRequestArgumentsFormatter.Serialize),
        [typeof(LaunchResponse)] = ((DeserializeDelegate<LaunchResponse>)LaunchResponseFormatter.Deserialize, (SerializeDelegate<LaunchResponse>)LaunchResponseFormatter.Serialize),
        [typeof(AttachRequest)] = ((DeserializeDelegate<AttachRequest>)AttachRequestFormatter.Deserialize, (SerializeDelegate<AttachRequest>)AttachRequestFormatter.Serialize),
        [typeof(AttachRequestArguments)] = ((DeserializeDelegate<AttachRequestArguments>)AttachRequestArgumentsFormatter.Deserialize, (SerializeDelegate<AttachRequestArguments>)AttachRequestArgumentsFormatter.Serialize),
        [typeof(AttachResponse)] = ((DeserializeDelegate<AttachResponse>)AttachResponseFormatter.Deserialize, (SerializeDelegate<AttachResponse>)AttachResponseFormatter.Serialize),
        [typeof(DisconnectRequest)] = ((DeserializeDelegate<DisconnectRequest>)DisconnectRequestFormatter.Deserialize, (SerializeDelegate<DisconnectRequest>)DisconnectRequestFormatter.Serialize),
        [typeof(DisconnectArguments)] = ((DeserializeDelegate<DisconnectArguments>)DisconnectArgumentsFormatter.Deserialize, (SerializeDelegate<DisconnectArguments>)DisconnectArgumentsFormatter.Serialize),
        [typeof(DisconnectResponse)] = ((DeserializeDelegate<DisconnectResponse>)DisconnectResponseFormatter.Deserialize, (SerializeDelegate<DisconnectResponse>)DisconnectResponseFormatter.Serialize),
        [typeof(TerminateRequest)] = ((DeserializeDelegate<TerminateRequest>)TerminateRequestFormatter.Deserialize, (SerializeDelegate<TerminateRequest>)TerminateRequestFormatter.Serialize),
        [typeof(TerminateArguments)] = ((DeserializeDelegate<TerminateArguments>)TerminateArgumentsFormatter.Deserialize, (SerializeDelegate<TerminateArguments>)TerminateArgumentsFormatter.Serialize),
        [typeof(TerminateResponse)] = ((DeserializeDelegate<TerminateResponse>)TerminateResponseFormatter.Deserialize, (SerializeDelegate<TerminateResponse>)TerminateResponseFormatter.Serialize),
        [typeof(SetBreakpointsRequest)] = ((DeserializeDelegate<SetBreakpointsRequest>)SetBreakpointsRequestFormatter.Deserialize, (SerializeDelegate<SetBreakpointsRequest>)SetBreakpointsRequestFormatter.Serialize),
        [typeof(SetBreakpointsArguments)] = ((DeserializeDelegate<SetBreakpointsArguments>)SetBreakpointsArgumentsFormatter.Deserialize, (SerializeDelegate<SetBreakpointsArguments>)SetBreakpointsArgumentsFormatter.Serialize),
        [typeof(SetBreakpointsResponseBody)] = ((DeserializeDelegate<SetBreakpointsResponseBody>)SetBreakpointsResponseBodyFormatter.Deserialize, (SerializeDelegate<SetBreakpointsResponseBody>)SetBreakpointsResponseBodyFormatter.Serialize),
        [typeof(SetBreakpointsResponse)] = ((DeserializeDelegate<SetBreakpointsResponse>)SetBreakpointsResponseFormatter.Deserialize, (SerializeDelegate<SetBreakpointsResponse>)SetBreakpointsResponseFormatter.Serialize),
        [typeof(ContinueRequest)] = ((DeserializeDelegate<ContinueRequest>)ContinueRequestFormatter.Deserialize, (SerializeDelegate<ContinueRequest>)ContinueRequestFormatter.Serialize),
        [typeof(ContinueArguments)] = ((DeserializeDelegate<ContinueArguments>)ContinueArgumentsFormatter.Deserialize, (SerializeDelegate<ContinueArguments>)ContinueArgumentsFormatter.Serialize),
        [typeof(ContinueResponseBody)] = ((DeserializeDelegate<ContinueResponseBody>)ContinueResponseBodyFormatter.Deserialize, (SerializeDelegate<ContinueResponseBody>)ContinueResponseBodyFormatter.Serialize),
        [typeof(ContinueResponse)] = ((DeserializeDelegate<ContinueResponse>)ContinueResponseFormatter.Deserialize, (SerializeDelegate<ContinueResponse>)ContinueResponseFormatter.Serialize),
        [typeof(NextRequest)] = ((DeserializeDelegate<NextRequest>)NextRequestFormatter.Deserialize, (SerializeDelegate<NextRequest>)NextRequestFormatter.Serialize),
        [typeof(NextArguments)] = ((DeserializeDelegate<NextArguments>)NextArgumentsFormatter.Deserialize, (SerializeDelegate<NextArguments>)NextArgumentsFormatter.Serialize),
        [typeof(NextResponse)] = ((DeserializeDelegate<NextResponse>)NextResponseFormatter.Deserialize, (SerializeDelegate<NextResponse>)NextResponseFormatter.Serialize),
        [typeof(StepInRequest)] = ((DeserializeDelegate<StepInRequest>)StepInRequestFormatter.Deserialize, (SerializeDelegate<StepInRequest>)StepInRequestFormatter.Serialize),
        [typeof(StepInArguments)] = ((DeserializeDelegate<StepInArguments>)StepInArgumentsFormatter.Deserialize, (SerializeDelegate<StepInArguments>)StepInArgumentsFormatter.Serialize),
        [typeof(StepInResponse)] = ((DeserializeDelegate<StepInResponse>)StepInResponseFormatter.Deserialize, (SerializeDelegate<StepInResponse>)StepInResponseFormatter.Serialize),
        [typeof(StepOutRequest)] = ((DeserializeDelegate<StepOutRequest>)StepOutRequestFormatter.Deserialize, (SerializeDelegate<StepOutRequest>)StepOutRequestFormatter.Serialize),
        [typeof(StepOutArguments)] = ((DeserializeDelegate<StepOutArguments>)StepOutArgumentsFormatter.Deserialize, (SerializeDelegate<StepOutArguments>)StepOutArgumentsFormatter.Serialize),
        [typeof(StepOutResponse)] = ((DeserializeDelegate<StepOutResponse>)StepOutResponseFormatter.Deserialize, (SerializeDelegate<StepOutResponse>)StepOutResponseFormatter.Serialize),
        [typeof(PauseRequest)] = ((DeserializeDelegate<PauseRequest>)PauseRequestFormatter.Deserialize, (SerializeDelegate<PauseRequest>)PauseRequestFormatter.Serialize),
        [typeof(PauseArguments)] = ((DeserializeDelegate<PauseArguments>)PauseArgumentsFormatter.Deserialize, (SerializeDelegate<PauseArguments>)PauseArgumentsFormatter.Serialize),
        [typeof(PauseResponse)] = ((DeserializeDelegate<PauseResponse>)PauseResponseFormatter.Deserialize, (SerializeDelegate<PauseResponse>)PauseResponseFormatter.Serialize),
        [typeof(StackTraceRequest)] = ((DeserializeDelegate<StackTraceRequest>)StackTraceRequestFormatter.Deserialize, (SerializeDelegate<StackTraceRequest>)StackTraceRequestFormatter.Serialize),
        [typeof(StackTraceArguments)] = ((DeserializeDelegate<StackTraceArguments>)StackTraceArgumentsFormatter.Deserialize, (SerializeDelegate<StackTraceArguments>)StackTraceArgumentsFormatter.Serialize),
        [typeof(StackTraceResponseBody)] = ((DeserializeDelegate<StackTraceResponseBody>)StackTraceResponseBodyFormatter.Deserialize, (SerializeDelegate<StackTraceResponseBody>)StackTraceResponseBodyFormatter.Serialize),
        [typeof(StackTraceResponse)] = ((DeserializeDelegate<StackTraceResponse>)StackTraceResponseFormatter.Deserialize, (SerializeDelegate<StackTraceResponse>)StackTraceResponseFormatter.Serialize),
        [typeof(ScopesRequest)] = ((DeserializeDelegate<ScopesRequest>)ScopesRequestFormatter.Deserialize, (SerializeDelegate<ScopesRequest>)ScopesRequestFormatter.Serialize),
        [typeof(ScopesArguments)] = ((DeserializeDelegate<ScopesArguments>)ScopesArgumentsFormatter.Deserialize, (SerializeDelegate<ScopesArguments>)ScopesArgumentsFormatter.Serialize),
        [typeof(ScopesResponseBody)] = ((DeserializeDelegate<ScopesResponseBody>)ScopesResponseBodyFormatter.Deserialize, (SerializeDelegate<ScopesResponseBody>)ScopesResponseBodyFormatter.Serialize),
        [typeof(ScopesResponse)] = ((DeserializeDelegate<ScopesResponse>)ScopesResponseFormatter.Deserialize, (SerializeDelegate<ScopesResponse>)ScopesResponseFormatter.Serialize),
        [typeof(VariablesRequest)] = ((DeserializeDelegate<VariablesRequest>)VariablesRequestFormatter.Deserialize, (SerializeDelegate<VariablesRequest>)VariablesRequestFormatter.Serialize),
        [typeof(VariablesArgumentsFilter)] = ((DeserializeDelegate<VariablesArgumentsFilter>)VariablesArgumentsFilterFormatter.Deserialize, (SerializeDelegate<VariablesArgumentsFilter>)VariablesArgumentsFilterFormatter.Serialize),
        [typeof(VariablesArguments)] = ((DeserializeDelegate<VariablesArguments>)VariablesArgumentsFormatter.Deserialize, (SerializeDelegate<VariablesArguments>)VariablesArgumentsFormatter.Serialize),
        [typeof(VariablesResponseBody)] = ((DeserializeDelegate<VariablesResponseBody>)VariablesResponseBodyFormatter.Deserialize, (SerializeDelegate<VariablesResponseBody>)VariablesResponseBodyFormatter.Serialize),
        [typeof(VariablesResponse)] = ((DeserializeDelegate<VariablesResponse>)VariablesResponseFormatter.Deserialize, (SerializeDelegate<VariablesResponse>)VariablesResponseFormatter.Serialize),
        [typeof(ThreadsRequest)] = ((DeserializeDelegate<ThreadsRequest>)ThreadsRequestFormatter.Deserialize, (SerializeDelegate<ThreadsRequest>)ThreadsRequestFormatter.Serialize),
        [typeof(ThreadsResponseBody)] = ((DeserializeDelegate<ThreadsResponseBody>)ThreadsResponseBodyFormatter.Deserialize, (SerializeDelegate<ThreadsResponseBody>)ThreadsResponseBodyFormatter.Serialize),
        [typeof(ThreadsResponse)] = ((DeserializeDelegate<ThreadsResponse>)ThreadsResponseFormatter.Deserialize, (SerializeDelegate<ThreadsResponse>)ThreadsResponseFormatter.Serialize),
        [typeof(EvaluateRequest)] = ((DeserializeDelegate<EvaluateRequest>)EvaluateRequestFormatter.Deserialize, (SerializeDelegate<EvaluateRequest>)EvaluateRequestFormatter.Serialize),
        [typeof(EvaluateArguments)] = ((DeserializeDelegate<EvaluateArguments>)EvaluateArgumentsFormatter.Deserialize, (SerializeDelegate<EvaluateArguments>)EvaluateArgumentsFormatter.Serialize),
        [typeof(EvaluateResponseBody)] = ((DeserializeDelegate<EvaluateResponseBody>)EvaluateResponseBodyFormatter.Deserialize, (SerializeDelegate<EvaluateResponseBody>)EvaluateResponseBodyFormatter.Serialize),
        [typeof(EvaluateResponse)] = ((DeserializeDelegate<EvaluateResponse>)EvaluateResponseFormatter.Deserialize, (SerializeDelegate<EvaluateResponse>)EvaluateResponseFormatter.Serialize),
        [typeof(Capabilities)] = ((DeserializeDelegate<Capabilities>)CapabilitiesFormatter.Deserialize, (SerializeDelegate<Capabilities>)CapabilitiesFormatter.Serialize),
        [typeof(ExceptionBreakpointsFilter)] = ((DeserializeDelegate<ExceptionBreakpointsFilter>)ExceptionBreakpointsFilterFormatter.Deserialize, (SerializeDelegate<ExceptionBreakpointsFilter>)ExceptionBreakpointsFilterFormatter.Serialize),
        [typeof(Message)] = ((DeserializeDelegate<Message>)MessageFormatter.Deserialize, (SerializeDelegate<Message>)MessageFormatter.Serialize),
        [typeof(ColumnDescriptorType)] = ((DeserializeDelegate<ColumnDescriptorType>)ColumnDescriptorTypeFormatter.Deserialize, (SerializeDelegate<ColumnDescriptorType>)ColumnDescriptorTypeFormatter.Serialize),
        [typeof(ColumnDescriptor)] = ((DeserializeDelegate<ColumnDescriptor>)ColumnDescriptorFormatter.Deserialize, (SerializeDelegate<ColumnDescriptor>)ColumnDescriptorFormatter.Serialize),
        [typeof(Thread)] = ((DeserializeDelegate<Thread>)ThreadFormatter.Deserialize, (SerializeDelegate<Thread>)ThreadFormatter.Serialize),
        [typeof(SourcePresentationHint)] = ((DeserializeDelegate<SourcePresentationHint>)SourcePresentationHintFormatter.Deserialize, (SerializeDelegate<SourcePresentationHint>)SourcePresentationHintFormatter.Serialize),
        [typeof(Source)] = ((DeserializeDelegate<Source>)SourceFormatter.Deserialize, (SerializeDelegate<Source>)SourceFormatter.Serialize),
        [typeof(StackFramePresentationHint)] = ((DeserializeDelegate<StackFramePresentationHint>)StackFramePresentationHintFormatter.Deserialize, (SerializeDelegate<StackFramePresentationHint>)StackFramePresentationHintFormatter.Serialize),
        [typeof(StackFrame)] = ((DeserializeDelegate<StackFrame>)StackFrameFormatter.Deserialize, (SerializeDelegate<StackFrame>)StackFrameFormatter.Serialize),
        [typeof(Scope)] = ((DeserializeDelegate<Scope>)ScopeFormatter.Deserialize, (SerializeDelegate<Scope>)ScopeFormatter.Serialize),
        [typeof(Variable)] = ((DeserializeDelegate<Variable>)VariableFormatter.Deserialize, (SerializeDelegate<Variable>)VariableFormatter.Serialize),
        [typeof(VariablePresentationHint)] = ((DeserializeDelegate<VariablePresentationHint>)VariablePresentationHintFormatter.Deserialize, (SerializeDelegate<VariablePresentationHint>)VariablePresentationHintFormatter.Serialize),
        [typeof(SourceBreakpoint)] = ((DeserializeDelegate<SourceBreakpoint>)SourceBreakpointFormatter.Deserialize, (SerializeDelegate<SourceBreakpoint>)SourceBreakpointFormatter.Serialize),
        [typeof(BreakpointReason)] = ((DeserializeDelegate<BreakpointReason>)BreakpointReasonFormatter.Deserialize, (SerializeDelegate<BreakpointReason>)BreakpointReasonFormatter.Serialize),
        [typeof(Breakpoint)] = ((DeserializeDelegate<Breakpoint>)BreakpointFormatter.Deserialize, (SerializeDelegate<Breakpoint>)BreakpointFormatter.Serialize),
        [typeof(SteppingGranularity)] = ((DeserializeDelegate<SteppingGranularity>)SteppingGranularityFormatter.Deserialize, (SerializeDelegate<SteppingGranularity>)SteppingGranularityFormatter.Serialize),
        [typeof(ChecksumAlgorithm)] = ((DeserializeDelegate<ChecksumAlgorithm>)ChecksumAlgorithmFormatter.Deserialize, (SerializeDelegate<ChecksumAlgorithm>)ChecksumAlgorithmFormatter.Serialize),
        [typeof(Checksum)] = ((DeserializeDelegate<Checksum>)ChecksumFormatter.Deserialize, (SerializeDelegate<Checksum>)ChecksumFormatter.Serialize),
        [typeof(ValueFormat)] = ((DeserializeDelegate<ValueFormat>)ValueFormatFormatter.Deserialize, (SerializeDelegate<ValueFormat>)ValueFormatFormatter.Serialize),
        [typeof(StackFrameFormat)] = ((DeserializeDelegate<StackFrameFormat>)StackFrameFormatFormatter.Deserialize, (SerializeDelegate<StackFrameFormat>)StackFrameFormatFormatter.Serialize),
        [typeof(BreakpointMode)] = ((DeserializeDelegate<BreakpointMode>)BreakpointModeFormatter.Deserialize, (SerializeDelegate<BreakpointMode>)BreakpointModeFormatter.Serialize),
    };
    
    static class Cache<T>
    {
        public static readonly DeserializeDelegate<T>? Deserialize;
        public static readonly SerializeDelegate<T>? Serialize;
        
        static Cache()
        {
            if (Formatters.TryGetValue(typeof(T), out var __entry))
            {
                Deserialize = global::System.Runtime.CompilerServices.Unsafe.As<DeserializeDelegate<T>>(__entry.Deserialize);
                Serialize = global::System.Runtime.CompilerServices.Unsafe.As<SerializeDelegate<T>>(__entry.Serialize);
            }
        }
    }
    
    public static T Deserialize<T>(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions? options = null)
    {
        var del = Cache<T>.Deserialize;
        if (del is null) ThrowNotSupported<T>();
        return del!(utf8Json, options ?? NoJsonSerializerOptions.Default);
    }
    
    public static T Deserialize<T>(byte[] utf8Json, NoJsonSerializerOptions? options = null) => Deserialize<T>((global::System.ReadOnlySpan<byte>)utf8Json, options);
    
    public static void Serialize<T>(global::System.Buffers.IBufferWriter<byte> writer, T value, NoJsonSerializerOptions? options = null)
    {
        var del = Cache<T>.Serialize;
        if (del is null) ThrowNotSupported<T>();
        del!(writer, value, options ?? NoJsonSerializerOptions.Default);
    }
    
    public static byte[] SerializeToUtf8Bytes<T>(T value, NoJsonSerializerOptions? options = null)
    {
        var buffer = new global::System.Buffers.ArrayBufferWriter<byte>(256);
        Serialize<T>(buffer, value, options);
        return buffer.WrittenSpan.ToArray();
    }
    
    [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    static void ThrowNotSupported<T>()
    {
        throw new global::System.NotSupportedException("No formatter generated for " + typeof(T).FullName);
    }
}
